site_name: BADD Labs

#markdown_extensions:
#  - pymdownx.arithmatex:
#      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

pages:
- Home: 'index.md'
- Labs: 
    - 'Lab A1. Transaction exploration': 'labs/A1/README.md'
    - 'Lab A2. Smart-contract programming': 'labs/A2/README.md'
    - 'Lab A3. Blockchain mining': 'labs/A3/README.md'
    - 'Lab B1. DEX 1: Swap settlement': 'labs/B1/README.md'
    - 'Lab B2. DEX 2: AMM and pricing': 'labs/B2/README.md'
    - 'Lab B3. DEX security: Arbitrage': 'labs/B3/README.md'
    - 'Lab B4. DEX security: Sandwich': 'labs/B4/README.md'
- About: 'about.md'

#theme: readthedocs
